User.create!([
  {email: "dani@gmail.com", username: "daniisfine", gender: "female", password_digest: "$2a$12$vt27Ww3tjf.NzJOovu8d1O9JU6HI/RHMdWxcnwLA339yNiIBLl/A2", latitude: "26.54204", longitude: "-81.78415", zip_code: "33913", photo: "https://www.theworlds50best.com/filestore/jpg/Daniela-BFC-19-teaser.jpg"},
  {email: "claude@gmail.com", username: "claudeKnows", gender: "male", password_digest: "$2a$12$DiaYW5z.XOt11cRWgN0caeL8aMyjUKGg0Hs3vdaFLMWhuwHkGvbX2", latitude: "33.80742", longitude: "-118.18602", zip_code: "90806", photo: "https://images.sk-static.com/images/media/profile_images/artists/584519/huge_avatar"},
  {email: "malik@gmail.com", username: "malik33", gender: "male", password_digest: "$2a$12$0od4D.2xPO1UjIOaSRexg.sATquHjH0zB418XAjsttKtCzzLjTyoG", latitude: "41.95361", longitude: "-88.72205", zip_code: "60115", photo: "http://logoonline.mtvnimages.com/uri/mgid:ao:image:logotv.com:265454?quality=0.8&format=jpg"},
  {email: "marissa@gmail.com", username: "marissaSays", gender: "transexual", password_digest: "$2a$12$XkfdLDMPt.uo.TrxfGXX5ulU1.wdFKlN9dJribQBO59B4Y2n17Xm2", latitude: "41.87909", longitude: "12.4789", zip_code: "70873", photo: "https://lh3.googleusercontent.com/TT5ltqwSPddH1JhS_6lmYhSZ_bk-_o5rDbQcnfaNy5GHj9LS3zjIGorlkpuSFisOQFs7UZva70TJbuc6kHvORGI_HfoJJx--Vw=w1200-h630-rj-pp"},
  {email: "miles@gmail.com", username: "miles324", gender: "male", password_digest: "$2a$12$yW73KUPnHakHDNt3QeMoaeG8wK4QJ8SN97nY4bJBHw6R18rWgBRgW", latitude: "39.77986", longitude: "-104.98291", zip_code: "80216", photo: "https://i.pinimg.com/originals/70/03/e1/7003e1116cc4b92f7f902c154d194fd9.jpg"}, 
  {email: "madaline@gmail.com", username: "madaline", gender: "female", password_digest: "$2a$12$lUPutGsD4JvLk4gwmIYaX.m2MbvbwFhjyeNtzE4zh3OHTe2gYbguy", latitude: "39.97703", longitude: "-75.12687", zip_code: "19125", photo: "https://secure.gravatar.com/avatar/b870cc9e96866425ce90a741a2921be4?s=400&d=mm&r=g"},
  {email: "allen@gmail.com", username: "allen", gender: "male", password_digest: "$2a$12$.CBSOHOCOWnfM8quHaJQv.KQ/IQf0.pvj4s5Gbbd.bbCP2qxqGjpm", latitude: "30.45000", longitude: "-91.18000", zip_code: "70873", photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKS7ERZwh13JFB3zqiaU3-fTD90b3j5dtUqYWjNA6JUax_C8vvvw"},
  {email: "cheddar@gmail.com", username: "cheddar", gender: "male", password_digest: "$2a$12$x2a29yJLsMXf43XYvEbG3OWPdFZAVOEYpvwGeTmeUNGO3IwMHmWGm", latitude: "40.06284", longitude: "-105.28258", zip_code: "33233", photo: "https://upload.wikimedia.org/wikipedia/commons/6/66/An_up-close_picture_of_a_curious_male_domestic_shorthair_tabby_cat.jpg"},
  {email: "michelle@gmail.com", username: "michelleLovesDancing", gender: "female", password_digest: "$2a$12$Hz8HNnAbtyHM/1KIqYYJS.KPtTrzlPR6Rq.LUgnlFO89svRpC231S", latitude: "38.234553", longitude: "-122.760385", zip_code: "94952", photo: "https://www.indiewire.com/wp-content/uploads/2018/02/amma.jpg?w=763"},
  {email: "germaine@gmail.com", username: "germaineDreamin", gender: "male", password_digest: "$2a$12$m.M7yIg2B2.XUGiClEd7oeoVTGjLBvGwTrhaubvBYKE/1SyRsRR5W", latitude: "41.95361", longitude: "-88.72205", zip_code: "60115", photo: "https://cdn.24.co.za/files/Cms/General/d/7466/bbd80228592c4b51b29945e893c4ee9d.png"},
  {email: "gwen@gmail.com", username: "gwenDigsDreaming", gender: "female", password_digest: "$2a$12$f1Mbh0NRm5LJm8eMIF2A1e.hN3hT3hpD3j8DLzDP0IZQyHK11AaS2", latitude: "37.98189", longitude: "-122.04082", zip_code: "94520", photo: "https://thumbor.forbes.com/thumbor/1280x868/https%3A%2F%2Fblogs-images.forbes.com%2Fcarolinecastrillon%2Ffiles%2F2019%2F03%2FLauren-Pufpaf-1-1200x800.jpg"},
  {email: "barry@gmail.com", username: "barryBuriesBerries", gender: "male", password_digest: "$2a$12$oeAOzWPJtAeQ6flZ//d3feY4xp.GxTB5yEUaUgaAe/72bfzWVUUwC", latitude: "34.17884", longitude: "-118.82697", zip_code: "91362", photo: "http://www.thetimes.co.uk/imageserver/image/methode%2Ftimes%2Fprod%2Fweb%2Fbin%2Ffcf87fee-b5b0-11e8-849b-d1a6cd5e8545.jpg?crop=623%2C350%2C0%2C0&resize=685"},
  {email: "ned@gmail.com", username: "nedPics", gender: "male", password_digest: "$2a$12$c8DaQkJPR6rhjorcguNSA.PccQakZ/7s/R9CDNaFChij1znuUx6i6", latitude: "32.52579", longitude: "-94.74966", zip_code: "75601", photo: "https://images2.minutemediacdn.com/image/upload/c_crop,h_860,w_1529,x_54,y_0/f_auto,q_auto,w_1100/v1554826525/shape/mentalfloss/nedflanders_1692813.jpg"},
  {email: "naruto@gmail.com", username: "narutoPlayer", gender: "", password_digest: "$2a$12$Mx65l5j3fdes80GV18Nbb.NMmazYmUVrbiNWvVlIvYYtnZaydfmci", latitude: "45.50147", longitude: "-122.6457", zip_code: "97202", photo: "https://mad-photography.co.uk/wp-content/uploads/2018/06/MAD-Photography-London-actors-headshots-Rad-Radev.jpg"},
  {email: "jasmine@gmail.com", username: "jasmineFlower", gender: "female", password_digest: "$2a$12$f94lk8pKl7upG3coRQqoO..AViiX56Xa3y0PWLevKRXh88dFMrdRu", latitude: "40.658888", longitude: "-111.921624", zip_code: "84123", photo: "http://www.giantmanagement.com/wp-content/uploads/2017/02/Headshot-650x813.jpg"},
  {email: "kyla@gmail.com", username: "kylaKYLAkyla", gender: "female", password_digest: "$2a$12$18QqwweTj3fQ76h.4eW34u6eX5oxQ.43TrWBvJvkdl4Y2e/3FAyvC", latitude: "28.478614", longitude: "-100.278411", zip_code: "78860", photo: "https://astanatimes.com/wp-content/uploads/2019/01/Zhansaya_Abdumalik.jpg"},
  {email: "truman@gmail.com", username: "cleverpillar", gender: "male", password_digest: "$2a$12$pY7lO6aV78.mqUCKQit7ZuPseLDvTVJ93oqr0PiO0MiBV5J2k0KSu", latitude: "29.945205", longitude: "-95.259778", zip_code: "77396", photo: "http://whatsthehype.in/wp-content/uploads/2017/12/tushar.jpg"},
  {email: "skyler@gmail.com", username: "onyxSky", gender: "male", password_digest: "$2a$12$v2du3J9Oq9wsHaB4szTvf.VapbVK3q.v4bzUr1mobx.EVyL6FnJL.", latitude: "34.464259", longitude: "-96.179638", zip_code: "74556", photo: "https://www.brazenmodels.com.au/wp-content/uploads/2019/03/KYLE-MAIN-554x694.jpg"},
  {email: "stella@gmail.com", username: "stellaSips", gender: "female", password_digest: "$2a$12$uwddV9GMu3k1oPjp/lOpDOEdUo3ujv5ijNlIn0eYisYsPeAATBRmi", latitude: "34.0275", longitude: "-118.50983", zip_code: "90402", photo: "https://www.brazenmodels.com.au/wp-content/uploads/2019/03/BAYLEE-MULLEN-MAIN-554x694.jpg"},
  {email: "caroline@gmail.com", username: "idontCaroline", gender: "female", password_digest: "$2a$12$KVZECZcR8UT96ClMwnNxxuc1wVdJNp./dc.zrIVDmMO9EvwEsLMU2", latitude: "38.582405", longitude: "-76.700998", zip_code: "20608", photo: "https://amp.businessinsider.com/images/581250e6b28a64c9018b56bc-750-563.jpg"},
  {email: "asha@gmail.com", username: "ashaGrey", gender: "female", password_digest: "$2a$12$BbP/XHXtUu5zSKG16ddGF.kxWffsDj5cs4TVlb4bRZHttq74ZC2E.", latitude: "42.2637", longitude: "-84.41408", zip_code: "49202", photo: "https://www.bmc.edu.sa/images/academia/tutors/dr-iklass.jpg"},
  {email: "nico@gmail.com", username: "nicoLA", gender: "male", password_digest: "$2a$12$QrfqTHm68VWQIuANZOd4W.XR.GDDm51.SSQoV6/ekxN69vW1/4Yre", latitude: "43.01836", longitude: "-83.68394", zip_code: "48503", photo: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/gavin-leatherwood-discusses-chilling-adventures-of-sabrina-news-photo-1140214026-1554915874.jpg?crop=1.00xw:0.754xh;0,0.0602xh&resize=480:*"},
  {email: "dimitri@gmail.com", username: "deMEtree", gender: "male", password_digest: "$2a$12$9mJGIjcDGtegzgwfiBkvd.biz9HhKWXISgonUZDVQ0GvUWA6ZdrYK", latitude: "42.28989", longitude: "-87.95032", zip_code: "60048", photo: "https://cdn-img.instyle.com/sites/default/files/styles/684xflex/public/1476133215/101016-male-feminists-1.jpg?itok=SyMuj4rG"},
  {email: "mo@gmail.com", username: "mojojojo", gender: "male", password_digest: "$2a$12$9CliZE43edBL/KjHz2f4Pu4MBeCtedje3xL2t4PAJoTXpRTRbcrre", latitude: "39.64157", longitude: "-106.37828", zip_code: "81657", photo: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2017/02/21/12/lifestyle.jpg"},
  {email: "ari@gmail.com", username: "ariOutside", gender: "female", password_digest: "$2a$12$RJNrWb1VkeY.8ViImZ8eauB8JNFcK.IDLpMXEn.EDwjx.Bl9W.uqS", latitude: "39.51221", longitude: "-106.72981", zip_code: "81658", photo: "https://i.dmarge.com/2016/09/long-hair-men-3-1057x1100.jpg"},
  {email: "yuri@gmail.com", username: "yuri24", gender: "male", password_digest: "$2a$12$sIT0sIsca68Yz8PRSDQd0uFw9RsJ1MTBYPdQsXFRMu3IRrZ.oKGhG", latitude: "41.42527", longitude: "-87.9834", zip_code: "60442", photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFB62P0d8SAZ_JT1di-UUNDw3GkIBKNt_xtpEopOjhYkUKXKhi"},
  {email: "amber@gmail.com", username: "amberbabe", gender: "female", password_digest: "$2a$12$ad199IlSf9P5DvK411FfkuSSuIoPx79qCRz6bkutn6cmGM4EMkj3i", latitude: "41.42527", longitude: "-87.9834", zip_code: "60442", photo: "https://images.immediate.co.uk/production/volatile/sites/3/2019/01/Margot-RObbie-ab0d7fd.jpg?quality=90&resize=620,413"},
  {email: "nadia@gmail.com", username: "nadiaKnows", gender: "female", password_digest: "$2a$12$oEUXu2/ihqIOp0.NQPqhHu6Ypnckrk92G5s1.f5RNwPtuBSpiVTw2", latitude: "44.47459", longitude: "-73.20822", zip_code: "05401", photo: "https://d2r9nfiii89r0l.cloudfront.net/dimg/435x435/dimg/ingrid_cronin-knight.jpg"},
  {email: "mark@gmail.com", username: "marquee", gender: "male", password_digest: "$2a$12$HsrOLwyO8gEYYADJHm8tiehTNreyZUiMNz6/HCIf6KiEDYatJq9Dy", latitude: "41.815208", longitude: "-74.978854", zip_code: "12766", photo: "https://cdn.ussoccer.com/-/jssmedia/project/ussf/players/mnt/matt-miazga/matt-miazga.ashx?h=580&la=en-US&w=580&rev=4c3c5a4b08964603921616ed8bacf3a7&hash=0098F65E2E19AC687B6033A84B8078E9"},
  {email: "tyler@gmail.com", username: "tylerrrr", gender: "male", password_digest: "$2a$12$JAJdx832mkZvoNGkJsXOieOwY.NM4hSyOHS85PCiMtPHduEDohLIW", latitude: "41.90148", longitude: "-87.66257", zip_code: "60622", photo: "https://images1-fabric.practo.com/dr-shah-dupesh-1487048260-58a28e4455699.jpg"},
  {email: "brittany@gmail.com", username: "brittanysPillowThoughts", gender: "female", password_digest: "$2a$12$l4kmmpuzmEzVFoM.ENrmde0UpBff9JqiU9r6GrM7FETYoYr3FDIoy", latitude: "38.85904", longitude: "-76.96641", zip_code: "20020", photo: "https://cdn.theatlantic.com/assets/media/None/image_6483441/200.jpg?mod=1552424873"},
  {email: "estelle@gmail.com", username: "estellar", gender: "female", password_digest: "$2a$12$r02Zes0TEMZqJr9VIPGBROpttjMGTJRfhAJ1J3VQ3tG0NY6XuD6nW", latitude: "47.53436", longitude: "-122.35524", zip_code: "98146", photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhrY7CZygsS562ENDeiONqOsULQBx6zi-HgVOb5wr0O9cYc2rv"},
  {email: "derrick@gmail.com", username: "derrick", gender: "male", password_digest: "$2a$12$Fu9OIAycEIGN1ogLBDwDHO3jMKHpfhduiiEzo9VVGet58LN0.mrdS", latitude: "43.574514", longitude: "-72.643229", zip_code: "98104", photo: "https://res.cloudinary.com/kaitlynhiggins/image/upload/v1563265262/nfwiggq0bvuodhbg879k.jpg"},
  {email: "moustachio@gmail.com", username: "moustachio", gender: "male", password_digest: "$2a$12$.FI13Y9ieG7UL/3ZlKQtU.5AkBv1csNKQQnwiBveqWakvbTTdHy6W", latitude: "26.51638", longitude: "-81.99825", zip_code: "33902", photo: "https://res.cloudinary.com/kaitlynhiggins/image/upload/v1563323194/nahmcpzyv0hl4kk5cpd1.jpg"},
  {email: "jack@gmail.com", username: "jack", gender: "male", password_digest: "$2a$12$y22eIO3Kg.UscHKRDIZwTeODbLxbh9f5v./8.wOtWrQa35VtzudnC", latitude: "40.831378", longitude: "-85.628114", zip_code: "46702", photo: "https://www.menshairstylesnow.com/wp-content/uploads/2018/11/Best-Neck-Tattoo-Ideas.jpg"},
  {email: "janine@gmail.com", username: "janine", gender: "female", password_digest: "$2a$12$wu6drv7Sq0sv9sB9Veots.qGFB86dzC9j9wYMauh4I5P5pUY1whki", latitude: "39.154813", longitude: "-90.828184", zip_code: "63343", photo: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?cs=srgb&dl=beautiful-blur-blurred-background-733872.jpg&fm=jpg"}
])


Dream.create!([
  {user_id: 1, title: "Chili", content: "I was making chili at Harry Carays, and I needed to impress someone with it who was coming in - but the chili sucked. It was super flavorless. I was out of time, but I needed to spice it up! I shouted for jalapenos, chopped them up, and stirred them in without cooking the chili more. It didn't improve. I drizzled it with a sour cream mountain hoping the person would assume the chili was good originally, but made bland by all the sour cream.", image_url: "https://img.wonderhowto.com/img/03/28/63593894282173/0/oops-food-too-spicy-heres-fix.w1456.jpg", is_public: true},
  {user_id: 1, title: "Capture The Flag", content: "I was part of a social experiment where participants were living in forest patches and battling against each other. Wildlife was prevalent, many snakes and spiders everywhere. We were provided a ration of two tacos per day. I managed to get my hands on a couple extra special fish tacos that weren't supposed to be available to us, and got caught with the contraband. At one point I escaped death when our transportation vehicle was upended.", image_url: "https://cdn.imgbin.com/10/14/9/imgbin-island-taco-mexican-cuisine-food-bean-taco-fUSqSLvydjXkVbqeq6yU2Guk8.jpg", is_public: true},
  {user_id: 3, title: "Trampoline Keyboard", content: "I invented a trampoline that had a keyboard attached to it, which would go up and down as I bounced so I could play music while I jumped. It was sweet.", image_url: "https://www.edwinmsarmiento.com/wp-content/uploads/2014/12/dsc_9140-760x503.jpg", is_public: true},
  {user_id: 4, title: "Keys locked in car", content: "My keys locked themselves in my car! My car autolocked when I closed the door with my bag containing my keys inside. I was stuck in Iceland with a dying phone and a lone sandwich to keep me warm.", image_url: "", is_public: false},
  {user_id: 4, title: "Hiking, Burt and a Taco Stand", content: "I was hiking in the appalacian mountains with Burt Reynolds, and there was a man with a taco stand. Perplexed, but excited, I scooped two fish tacos and two al pastor. They were the best tacos I've ever had in my life. Burt had a taco salad instead.", image_url: "https://66.media.tumblr.com/tumblr_ljyyisQQtg1qb40pro1_1280.png", is_public: true},
  {user_id: 4, title: "Chased by penguins", content: "My friend Antoinette and I were in an ice rink having a jolly old time, and all of  a sudden the lights dimmed and the music got really dark and creepy... Penguins started to waddle onto the rink! I was excited, thinking someone was playing an awesome prank on us or that they were practicing for a show and we were lucky enough to be there to witness. Boy was I wrong. the penguins, while being cute and tiny, were hungry and vicious. They had razor sharp teeth, and they were chasing Antoinette and I around the rink!", image_url: "https://live.staticflickr.com/4092/4847551142_8c932864f4_b.jpg", is_public: false},
  {user_id: 4, title: "Trampoline Keyboard", content: "I invented a trampoline that had a keyboard attached to it, which would go up and down as I bounced so I could play music while I jumped. It was sweet.", image_url: "https://www.edwinmsarmiento.com/wp-content/uploads/2014/12/dsc_9140-760x503.jpg", is_public: false},
  {user_id: 4, title: "Hiking", content: "I was hiking in the appalacian mountains with Burt Reynolds, and there was a man with a taco stand. Perplexed, but excited, I scooped two fish tacos and two al pastor. They were the best tacos I've ever had in my life. Burt had a taco salad instead.", image_url: "https://66.media.tumblr.com/tumblr_ljyyisQQtg1qb40pro1_1280.png", is_public: true},
  {user_id: 3, title: "chased by killer dolphins", content: "i was chased! they lost.", image_url: "https://img.huffingtonpost.com/asset/5d0503742400005117924fdf.jpeg?cache=j9psni4qsj&ops=1910_1000", is_public: nil},
  {user_id: 4, title: "sailing", content: "I was sailing on a massive lake, filled with neat creatures. Dolphins kept following me, doing tricks and showing off. An owl stayed perched on the mast. His name was Oliver", image_url: "", is_public: nil},
  {user_id: 3, title: "dolphins", content: "i was chased! they lost.", image_url: "https://img.huffingtonpost.com/asset/5d0503742400005117924fdf.jpeg?cache=j9psni4qsj&ops=1910_1000", is_public: nil},
  {user_id: 1, title: "fjords", content: "I was exploring fjords in iceland, they were majestic. There were waterfalls all over.", image_url: "https://www.worldatlas.com/r/w728-h425-c728x425/upload/37/21/7d/shutterstock-309014675.jpg", is_public: nil},
  {user_id: 1, title: "Monkey", content: "I dreamt I was a monkey, swinging from the trees!", image_url: "https://i.pinimg.com/originals/f9/24/61/f924613d358446614d352d5d82edffd9.jpg", is_public: true},
  {user_id: 1, title: "lions eating cake", content: "There were talking lions and they were eating cake", image_url: "http://i.imgur.com/zbXidCL.jpg", is_public: true},
  {user_id: 1, title: "Mules on a ship", content: "there were mules on a ship eating popcorn", image_url: "", is_public: true},
  {user_id: 2, title: "Rainbows Upside Down", content: "Rainbows were everywhere. Some were upside down!", image_url: "https://sp-images.summitpost.org/805052.jpg?auto=format&fit=max&ixlib=php-2.1.1&q=35&w=1024&s=34130ea83488a802fc2e2054e5d88abe", is_public: true},
  {user_id: 2, title: "Chili Fail", content: "I was making chili at Harry Carays, and I needed to impress someone with it who was coming in - but the chili sucked. It was super flavorless. I was out of time, but I needed to spice it up! I shouted for jalapenos, chopped them up, and stirred them in without cooking the chili more. It didn't improve. I drizzled it with a sour cream mountain hoping the person would assume the chili was good originally, but made bland by all the sour cream.", image_url: "https://img.wonderhowto.com/img/03/28/63593894282173/0/oops-food-too-spicy-heres-fix.w1456.jpg", is_public: true},
  {user_id: 2, title: "Pickles TALK!", content: "I was surrounded by pickles... And they could talk!", image_url: "https://www.robertjweisberg.com/content/images/2016/04/pickle-on-line-1.jpeg", is_public: true},
  {user_id: 2, title: "Capture The Flag", content: "I was part of a social experiment where participants were living in forest patches and battling against each other. Wildlife was prevalent, many snakes and spiders everywhere. We were provided a ration of two tacos per day. I managed to get my hands on a couple extra special fish tacos that weren't supposed to be available to us, and got caught with the contraband. At one point I escaped death when our transportation vehicle was upended. Woah!", image_url: "https://cdn.imgbin.com/10/14/9/imgbin-island-taco-mexican-cuisine-food-bean-taco-fUSqSLvydjXkVbqeq6yU2Guk8.jpg", is_public: true},
  {user_id: 2, title: "My son moved to Berlin", content: "Shane and Katie moved to Berlin! I went to visit them a few weeks after they moved and we went sight seeing, and hit the dance floor to boogie!", image_url: "https://media.globalchampionsleague.com/cache/750x429/assets/berlin.jpg", is_public: nil},
  {user_id: 1, title: "Kitten was laying", content: "Kitten was laying on the warm computer charger. Then he sneezed.", image_url: "https://mypetandi.bayer.com/sites/g/files/kmftyc426/files/styles/paragraph_image/public/2018-03/kitten_rescue_00821_4.jpg?itok=pbvTgpU5", is_public: true},
  {user_id: 1, title: "can't find keys", content: "couldn't find my keys and it made me late for work.", image_url: "https://cdn.shopify.com/s/files/1/0624/1921/products/Keys_50596a6f-e305-4fd0-b434-3d78647c3825.jpg?v=1495936865", is_public: true},
  {user_id: 1, title: "testing", content: "it takes forever", image_url: "http://i.imgur.com/zbXidCL.jpg", is_public: true},
  {user_id: 1, title: "i'm begging", content: "you to work", image_url: "https://mypetandi.bayer.com/sites/g/files/kmftyc426/files/styles/paragraph_image/public/2018-03/kitten_rescue_00821_4.jpg?itok=pbvTgpU5", is_public: true},
  {user_id: 1, title: "and right", content: "rawr", image_url: "https://cdn.shopify.com/s/files/1/0624/1921/products/Keys_50596a6f-e305-4fd0-b434-3d78647c3825.jpg?v=1495936865", is_public: true},
  {user_id: 6, title: "Skating with Auntie J", content: "I was skateboarding with Aunt Jemima! She was killin' it. ", image_url: "https://i.udemycdn.com/course/750x422/124798_5f7d_10.jpg", is_public: true},
  {user_id: 7, title: "Lion eating a computer", content: "A lion was munching on my computer while laying on top of a giant cake. Why not eat the cake instead??", image_url: "http://i.imgur.com/ej8sJ.png", is_public: true},
  {user_id: 1, title: "Kitten causing trouble", content: "My kitten was swinging from the rafters", image_url: "", is_public: true},
  {user_id: 1, title: "Mouse trap", content: "I was in a giant game of mouse trap", image_url: "https://i.ytimg.com/vi/t-TZRDvBjyc/maxresdefault.jpg", is_public: true},
  {user_id: 1, title: "Dino talent", content: "A volcano erupted, and with it came a t-rex wearing blazing gold skis, skiing down the lava.", image_url: "https://i.ytimg.com/vi/1vMBqDt0s0I/hqdefault.jpg", is_public: true},
  {user_id: 9, title: "Eating an apple", content: "I was eating an apple and peanut butter on a bridge, overlooking a waterfall.", image_url: "https://img.sndimg.com/food/image/upload/w_555,h_416,c_fit,fl_progressive,q_95/v1/img/recipes/21/83/90/picZLz4xF.jpg", is_public: true},
  {user_id: 8, title: "Went to Japan", content: "I went to Japan on a massive cruise ship!", image_url: "https://rccl-h.assetsadobe.com/is/image/content/dam/royal/content/fleet-landing/harmony-exterior-back-aerial-day-sailing-ship.JPG?$750x400$", is_public: true},
  {user_id: 4, title: "fjords", content: "I was exploring fjords in iceland, they were majestic. There were waterfalls all over.", image_url: "https://www.worldatlas.com/r/w728-h425-c728x425/upload/37/21/7d/shutterstock-309014675.jpg", is_public: nil},
  {user_id: 4, title: "It was raining colors", content: "It was pouring outside, but it was super bright and everything was colorful - including the raindrops! There were 4 rainbows in the sky, one in each direction. They overlapped in the center and met in the middle, right at my feet!", image_url: "https://img.purch.com/w/660/aHR0cDovL3d3dy5saXZlc2NpZW5jZS5jb20vaW1hZ2VzL2kvMDAwLzEwMS85NzUvb3JpZ2luYWwvc3VwZXJudW1lcmFyeS1yYWluYm93LmpwZw==", is_public: true},
  {user_id: 3, title: "chased by killer dolphins", content: "i was chased! they lost.", image_url: "https://img.huffingtonpost.com/asset/5d0503742400005117924fdf.jpeg?cache=j9psni4qsj&ops=1910_1000", is_public: true},
  {user_id: 2, title: "This is not a test", content: "I was taking a test to become a certified outdoorsman. It started out pretty simple - I had to find cows and feed them certain foods depending on what color their spots were. Then I had to build a treehouse. From the treehouse I saw dolphins leaping over a barricade, so I had to feed those that made it over okeedoke popcorn.", image_url: "https://treehouseutopia.com/wp-content/uploads/2018/07/Chapelle-west-view-1024x1024.jpg", is_public: true},
  {user_id: 2, title: "I went to Electric Forest", content: "I went to Electric Forest music festival and it was beautiful in every way. We were camped by our friends and every night we had a huge party at our campsite every night after the festival. ", image_url: "http://downbeats.com/wp-content/uploads/Sherwood-Forest-EF.jpg", is_public: true},
  {user_id: 1, title: "monkey eating", content: "monkeys and mules were eating a pancake", image_url: "https://image.shutterstock.com/image-photo/portrait-funny-little-monkey-eating-260nw-1410453653.jpg", is_public: true},
  {user_id: 2, title: "Floating Through the Sky", content: "I was floating through the sky in a hot air balloon with 5 of my closest friends. We had a picnic, enjoyed the mountainous scenery, and made friends with some birds. It was beautiful. I want to go back!", image_url: "https://www.ballooningintuscany.com/wp-content/uploads/2019/05/199-7.jpg", is_public: true},
  {user_id: 49, title: "Dancing in a field", content: "I was dancing in a big, beautiful lush field with my friends. The music was glitchy and intelligent, and the breeze was perfect. ", image_url: "https://www.pandotrip.com/wp-content/uploads/2014/09/Top-10-Flowery-Fields-Grand-Teton-740x555.jpg", is_public: true},
  {user_id: 2, title: "churros dancing and dipping", content: "I was riding my bike to go fetch some churros, when a bunny hopped out in front of my bike. I slammed on the brakes and flew off of the bike, missing the bunny. The bunny's owner ran down the street and thanked me for stopping, apologized that I got grass stains all over my clothes, and offered me free churros for life at his mexican restuarant, which I was on my way to in the first place!", image_url: "https://media1.tenor.com/images/4361f579a306bfd001c12c77cdf5c024/tenor.gif?itemid=10759370", is_public: true},
  {user_id: 10, title: "The Terrain Was Rocky", content: "It was kind of a flashback of when I went to Mt. Hood in Oregon, the mountains were dry and rocky, and the crunch of stones beneath my boots was doing a number on the soles of my favorite pair. The sun was starting to set and very quickly the temperature dropped from 90's all the way down to 50's. ", image_url: "https://www.timberlinelodge.com/images/1_col/ACTIVITES_1C_MOUNTAINEERING-5a738a22e5d62-1374-1517521442.jpg", is_public: true},
  {user_id: 2, title: "Stomach Ache", content: "My stomach ached like crazy. I was super tired but I couldn't go to sleep because I had to finish my capstone project. Then it was 5 am.", image_url: "https://media1.tenor.com/images/4361f579a306bfd001c12c77cdf5c024/tenor.gif?itemid=10759370", is_public: true}
])
Tag.create!([
  {dream_id: 42, name: "glitch"},
  {dream_id: 42, name: "music"},
  {dream_id: 42, name: "weird"},
  {dream_id: 42, name: "friends"},
  {dream_id: 42, name: "wiggle"},
  {dream_id: 42, name: "dancing"},
  {dream_id: 42, name: "nature"},
  {dream_id: 42, name: "bubbles"},
  {dream_id: 42, name: "air"},
  {dream_id: 42, name: "fresh"},
  {dream_id: 42, name: "floating"},
  {dream_id: 12, name: "rainbows"},
  {dream_id: 12, name: "upsideDownRainbows"},
  {dream_id: 12, name: "upsideDown"},
  {dream_id: 28, name: "kitten"},
  {dream_id: 28, name: "computer"},
  {dream_id: 28, name: "charge"},
  {dream_id: 29, name: "cant"},
  {dream_id: 29, name: "find"},
  {dream_id: 29, name: "keys"},
  {dream_id: 41, name: "balloon"},
  {dream_id: 43, name: "adventure"},
  {dream_id: 43, name: "terrain"},
  {dream_id: 43, name: "temperature"},
  {dream_id: 13, name: "chased"},
  {dream_id: 13, name: "penguins"},
  {dream_id: 13, name: "angry"},
  {dream_id: 34, name: "skateboarding"},
  {dream_id: 34, name: "chicago"},
  {dream_id: 34, name: "auntjemima"},
  {dream_id: 35, name: "skateboarding"},
  {dream_id: 35, name: "chicago"},
  {dream_id: 35, name: "auntjemima"},
  {dream_id: 15, name: "berlin"},
  {dream_id: 15, name: "son"},
  {dream_id: 15, name: "farFarAway"},
  {dream_id: 7, name: "berlin"},
  {dream_id: 7, name: "son"},
  {dream_id: 7, name: "farFarAway"},
  {dream_id: 36, name: "skateboarding"},
  {dream_id: 36, name: "chicago"},
  {dream_id: 36, name: "auntjemima"},
  {dream_id: 37, name: "lion"},
  {dream_id: 37, name: "computer"},
  {dream_id: 37, name: "cake"},
  {dream_id: 38, name: "kitten"},
  {dream_id: 38, name: "swinging"},
  {dream_id: 38, name: "cable"},
  {dream_id: 5, name: "try"},
  {dream_id: 5, name: "again"},
  {dream_id: 5, name: "dude"},
  {dream_id: 9, name: "mouse"},
  {dream_id: 9, name: "trap"},
  {dream_id: 9, name: "giant"},
  {dream_id: 17, name: "dolphin"},
  {dream_id: 17, name: "chase"},
  {dream_id: 17, name: "killer"},
  {dream_id: 5, name: "travel"},
  {dream_id: 5, name: "japan"},
  {dream_id: 5, name: "boat"},
  {dream_id: 7, name: "mango"},
  {dream_id: 28, name: "mango"},
  {dream_id: 11, name: "capture"},
  {dream_id: 11, name: "flag"},
  {dream_id: 11, name: "social"},
  {dream_id: 11, name: "experiment"},
  {dream_id: 11, name: "tacos"},
  {dream_id: 11, name: "escape"},
  {dream_id: 40, name: "electricforest"},
  {dream_id: 40, name: "festival"},
  {dream_id: 40, name: "colors"},
  {dream_id: 40, name: "adventure"},
  {dream_id: 40, name: "beautiful"},
  {dream_id: 40, name: "dancing"},
  {dream_id: 3, name: "social"},
  {dream_id: 3, name: "experiment"},
  {dream_id: 3, name: "adventure"},
  {dream_id: 3, name: "tacos"},
  {dream_id: 3, name: "capture"},
  {dream_id: 3, name: "battle"},
  {dream_id: 3, name: "forest"},
  {dream_id: 3, name: "colors"},
  {dream_id: 3, name: "everywhere"},
  {dream_id: 3, name: "wildlife"},
  {dream_id: 3, name: "free"},
  {dream_id: 19, name: "fjords"},
  {dream_id: 19, name: "exploring"},
  {dream_id: 19, name: "adventure"},
  {dream_id: 19, name: "iceland"},
  {dream_id: 19, name: "water"},
  {dream_id: 19, name: "waterfalls"},
  {dream_id: 19, name: "beautiful"},
  {dream_id: 19, name: "nature"},
  {dream_id: 19, name: "colors"},
  {dream_id: 19, name: "wildlife"},
  {dream_id: 19, name: "find"},
  {dream_id: 20, name: "monkey"},
  {dream_id: 20, name: "swinging"},
  {dream_id: 20, name: "trees"},
  {dream_id: 20, name: "beautiful"},
  {dream_id: 20, name: "colorful"},
  {dream_id: 20, name: "adventure"},
  {dream_id: 20, name: "nature"},
  {dream_id: 20, name: "waterfalls"},
  {dream_id: 20, name: "owl"},
  {dream_id: 20, name: "upsidedown"},
  {dream_id: 20, name: "everywhere"},
  {dream_id: 21, name: "lions"},
  {dream_id: 21, name: "eating"},
  {dream_id: 21, name: "cake"},
  {dream_id: 21, name: "talkinglions"},
  {dream_id: 21, name: "adventure"},
  {dream_id: 21, name: "nature"},
  {dream_id: 21, name: "beautiful"},
  {dream_id: 21, name: "nature"},
  {dream_id: 21, name: "hungry"},
  {dream_id: 21, name: "cute"},
  {dream_id: 21, name: "travel"},
  {dream_id: 22, name: "mules"},
  {dream_id: 22, name: "ship"},
  {dream_id: 22, name: "onaboat"},
  {dream_id: 22, name: "popcorn"},
  {dream_id: 22, name: "eating"},
  {dream_id: 22, name: "water"},
  {dream_id: 22, name: "sailing"},
  {dream_id: 22, name: "nature"},
  {dream_id: 22, name: "animal"},
  {dream_id: 22, name: "adventure"},
  {dream_id: 22, name: "tasty"},
  {dream_id: 23, name: "kitten"},
  {dream_id: 23, name: "cute"},
  {dream_id: 23, name: "tiny"},
  {dream_id: 23, name: "warm"},
  {dream_id: 23, name: "sneeze"},
  {dream_id: 23, name: "adorable"},
  {dream_id: 23, name: "laying"},
  {dream_id: 23, name: "cutesneeze"},
  {dream_id: 23, name: "hilarious"},
  {dream_id: 23, name: "animal"},
  {dream_id: 23, name: "beautiful"},
  {dream_id: 24, name: "keys"},
  {dream_id: 24, name: "fail"},
  {dream_id: 24, name: "late"},
  {dream_id: 24, name: "lateforwork"},
  {dream_id: 24, name: "ugh"},
  {dream_id: 24, name: "anger"},
  {dream_id: 24, name: "nightmare"},
  {dream_id: 24, name: "morningstruggles"},
  {dream_id: 24, name: "ihatemornings"},
  {dream_id: 24, name: "thankfulitsadream"},
  {dream_id: 24, name: "lostkeys"},
  {dream_id: 25, name: "forever"},
  {dream_id: 25, name: "test"},
  {dream_id: 25, name: "colorful"},
  {dream_id: 25, name: "beautiful"},
  {dream_id: 25, name: "everywhere"},
  {dream_id: 25, name: "adventure"},
  {dream_id: 25, name: "rainbows"},
  {dream_id: 25, name: "dancing"},
  {dream_id: 25, name: "giant"},
  {dream_id: 25, name: "chicago"},
  {dream_id: 25, name: "skateboard"},
  {dream_id: 26, name: "work"},
  {dream_id: 26, name: "beg"},
  {dream_id: 26, name: "kitten"},
  {dream_id: 26, name: "cat"},
  {dream_id: 26, name: "adventure"},
  {dream_id: 26, name: "color"},
  {dream_id: 26, name: "beautiful"},
  {dream_id: 26, name: "fail"},
  {dream_id: 26, name: "changing"},
  {dream_id: 26, name: "chicago"},
  {dream_id: 26, name: "mango"},
  {dream_id: 27, name: "popcorn"},
  {dream_id: 27, name: "mule"},
  {dream_id: 27, name: "ship"},
  {dream_id: 27, name: "beautiful"},
  {dream_id: 27, name: "colors"},
  {dream_id: 27, name: "chicago"},
  {dream_id: 27, name: "skateboard"},
  {dream_id: 27, name: "lion"},
  {dream_id: 27, name: "dino"},
  {dream_id: 27, name: "eating"},
  {dream_id: 27, name: "happy"},
  {dream_id: 30, name: "kitten"},
  {dream_id: 30, name: "swinging"},
  {dream_id: 30, name: "rafters"},
  {dream_id: 30, name: "adventure"},
  {dream_id: 30, name: "hilarious"},
  {dream_id: 30, name: "cute"},
  {dream_id: 30, name: "trouble"},
  {dream_id: 30, name: "busted"},
  {dream_id: 30, name: "laughing"},
  {dream_id: 30, name: "beautiful"},
  {dream_id: 30, name: "love"},
  {dream_id: 31, name: "giant"},
  {dream_id: 31, name: "game"},
  {dream_id: 31, name: "mouse"},
  {dream_id: 31, name: "mousetrap"},
  {dream_id: 31, name: "awesome"},
  {dream_id: 31, name: "adventure"},
  {dream_id: 31, name: "hilarious"},
  {dream_id: 31, name: "chicago"},
  {dream_id: 31, name: "eating"},
  {dream_id: 31, name: "cheese"},
  {dream_id: 31, name: "dancing"},
  {dream_id: 32, name: "monkeys"},
  {dream_id: 32, name: "mules"},
  {dream_id: 32, name: "eating"},
  {dream_id: 32, name: "pancakes"},
  {dream_id: 32, name: "cute"},
  {dream_id: 32, name: "nature"},
  {dream_id: 32, name: "food"},
  {dream_id: 32, name: "hilarious"},
  {dream_id: 32, name: "adventure"},
  {dream_id: 32, name: "colorful"},
  {dream_id: 32, name: "cute"},
  {dream_id: 33, name: "dino"},
  {dream_id: 33, name: "skiing"},
  {dream_id: 33, name: "volcano"},
  {dream_id: 33, name: "trex"},
  {dream_id: 33, name: "lava"},
  {dream_id: 33, name: "blazing"},
  {dream_id: 33, name: "goldskis"},
  {dream_id: 33, name: "fire"},
  {dream_id: 33, name: "eruption"},
  {dream_id: 33, name: "awesome"},
  {dream_id: 33, name: "adventure"},
  {dream_id: 14, name: "berlinlove"},
  {dream_id: 14, name: "dancing"},
  {dream_id: 14, name: "dancefloor"},
  {dream_id: 14, name: "son"},
  {dream_id: 14, name: "adventure"},
  {dream_id: 14, name: "beautiful"},
  {dream_id: 39, name: "treehouse"},
  {dream_id: 39, name: "dolphinsleaping"},
  {dream_id: 39, name: "okeedokee"},
  {dream_id: 1, name: "chili"},
  {dream_id: 1, name: "harrycarays"},
  {dream_id: 1, name: "notspicy"},
  {dream_id: 1, name: "adventure"}
])
Theme.create!([
  {name: "Lucid"},
  {name: "Nightmare"},
  {name: "Memory"},
  {name: "Adventure"},
  {name: "Recurring"},
  {name: "Healing"},
  {name: "inspiration"}
])
DreamTheme.create!([
  {dream_id: 41, theme_id: 1},
  {dream_id: 41, theme_id: 1},
  {dream_id: 39, theme_id: 1},
  {dream_id: 39, theme_id: 2},
  {dream_id: 39, theme_id: 3},
  {dream_id: 43, theme_id: 4},
  {dream_id: 43, theme_id: 3},
  {dream_id: 1, theme_id: 2},
  {dream_id: 1, theme_id: 7},
  {dream_id: 1, theme_id: 4},
  {dream_id: 42, theme_id: 6},
  {dream_id: 42, theme_id: 7},
  {dream_id: 42, theme_id: 4},
  {dream_id: 4, theme_id: 1},
  {dream_id: 4, theme_id: 4},
  {dream_id: 4, theme_id: 6},
  {dream_id: 4, theme_id: 7}
])

